const data = [
    
    {   id : 1,
        title  : "Purpose of front end and back end",
        content : "The back end refers to parts of a computer application or a program's code that allow it to operate and that cannot be accessed by a user. Most data and operating syntax are stored and accessed in the back end of a computer system. Typically the code is comprised of one or more programming languages. The back end is also called the data access layer of software or hardware and includes any functionality that needs to be accessed and navigated to by digital means. The layer above the back end is the front end and it includes all software or hardware that is part of a user interface. Human or digital users interact directly with various aspects of the front end of a program, including user-entered data, buttons, programs, websites and other features. Most of these features are designed by user experience (UX) professionals to be accessible, pleasant and easy to use.A back-end application or program supports front-end user services, and interfaces with any required resources. The back-end application may interact directly with the front end or it may be called from an intermediate program that mediates front-end and back-end activities.System architectures are broken down into front end and back end components for a variety of purposes. The most common is in software and web development to break down projects in terms of required skills. The front end aspect of a project is usually handled by professionals such as web designers while the back end is handled by engineers and developers.Front end and back end can also be used to describe situations where the customer has access to one view and employees have access to another. Front end components are customer facing while rights to the back end are exclusively for authenticated users.",
        author  : "Price"

    },
    {   id : 2,
        title  : "A Brief History of JavaScript",
        content : "JavaScript is a programming language that represents one of the three core languages used to develop websites, alongside HTML and CSS. Whereas HTML and CSS give a website structure and style, JavaScript lets you add functionality and behaviors to your website. This allows visitors to interact with your website in various creative ways.Mosaic was the first web browser with a graphical user interface. It was first released in 1993 and played a key role in the rapid development of the web as we know it today. The lead developers of Mosaic founded Netscape (now Mozilla) and released a more elegant browser called Netscape Navigator in 1994.During the early years of the web, web pages were only static, with no capability for dynamic behavior and interactivity. As a result, there was an urge in the web development community at the time to eliminate this limitation. This led Netscape to the decision to add a scripting language to the Navigator browser.In September 1995, a Netscape programmer named Brendan Eich developed a new scripting language in just 10 days. It was originally called Mocha, but quickly became known as LiveScript and, later, JavaScript.In September 1995, a Netscape programmer named Brendan Eich developed a new scripting language in just 10 days. It was originally called Mocha, but quickly became known as LiveScript and, later, JavaScript.According to GitHub’s 2021 Octoverse report, there are more JavaScript code repositories than any other language, and that number is steadily on the rise.JavaScript can be found virtually everywhere on the Internet. It has been named the most widely used programming language several times with over 64.9 percent of developers using it in 2021.A series of JavaScript frameworks and libraries such as Ember, Angular, React, and Vue have also been created to develop powerful and complicated web applications. Also, alongside client and server software, it is now even possible to write native mobile apps using JavaScript.",
        author  : "Ghost"

    },
    {   id : 3,
        title  : "What is blockchain technology?",
        content : "Blockchain defined: Blockchain is a shared, immutable ledger that facilitates the process of recording transactions and tracking assets in a business network. An asset can be tangible (a house, car, cash, land) or intangible (intellectual property, patents, copyrights, branding). Virtually anything of value can be tracked and traded on a blockchain network, reducing risk and cutting costs for all involved.Business runs on information. The faster it’s received and the more accurate it is, the better. Blockchain is ideal for delivering that information because it provides immediate, shared and completely transparent information stored on an immutable ledger that can be accessed only by permissioned network members. A blockchain network can track orders, payments, accounts, production and much more. And because members share a single view of the truth, you can see all details of a transaction end to end, giving you greater confidence, as well as new efficiencies and opportunities.Operations often waste effort on duplicate record keeping and third-party validations. Record-keeping systems can be vulnerable to fraud and cyberattacks. Limited transparency can slow data verification. And with the arrival of IoT, transaction volumes have exploded. All of this slows business, drains the bottom line — and means we need a better way. Enter blockchain.",
        author  : "Gaz"

    },
    {   id : 4,
        title  : "What is Bitcoin mining?",
        content : "Bitcoin mining is the process of creating new bitcoins by solving extremely complicated math problems that verify transactions in the currency. When a bitcoin is successfully mined, the miner receives a predetermined amount of bitcoin.Bitcoin is a cryptocurrency that’s gained wide popularity due to its wild price swings and surging value since it was first created in 2009.As prices of cryptocurrencies and Bitcoin in particular have skyrocketed in recent years, it’s understandable that interest in mining has picked up as well. But for most people, the prospects for Bitcoin mining are not good due to its complex nature and high costs. Here are the basics on how Bitcoin mining works and some key risks to be aware of.Bitcoin is one of the most popular types of cryptocurrencies, which are digital mediums of exchange that exist solely online. Bitcoin runs on a decentralized computer network or distributed ledger that tracks transactions in the cryptocurrency. When computers on the network verify and process transactions, new bitcoins are created, or mined. These networked computers, or miners, process the transaction in exchange for a payment in Bitcoin.Bitcoin is powered by blockchain, which is the technology that powers many cryptocurrencies. A blockchain is a decentralized ledger of all the transactions across a network. Groups of approved transactions together form a block and are joined to create a chain. Think of it as a long public record that functions almost like a long running receipt. Bitcoin mining is the process of adding a block to the chain.",
        author  : "Soap"

    },
]
export default data;